import * as THREE from "three";

export type ConstructionGroup = { name: string; width: number; height: number; depth: number; position: { x: number; y: number; z: number }; material: string; triangles: number; anchor: Anchor };
export type ConstructionItem = { itemId: string; kind: string; color: string; groups: ConstructionGroup[] };
export type RenderedMeasurement = { itemId: string; groupName: string; expected: [number, number, number]; rendered: [number, number, number]; worldPosition: [number, number, number]; triangles: number; material: string; passed: boolean };
export type RenderedGeometryVerificationReport = { generationId: string; passed: boolean; measurements: RenderedMeasurement[]; missingGroups: string[] };
export type Anchor = "head" | "neck" | "torso" | "waist" | "leftLeg" | "rightLeg" | "leftFoot" | "rightFoot";

export const AVATAR_ANCHORS: Record<Anchor, [number, number, number]> = { head:[0,2.05,0], neck:[0,1.72,0], torso:[0,1.35,0], waist:[0,.82,0], leftLeg:[-.22,.48,0], rightLeg:[.22,.48,0], leftFoot:[-.22,.08,.04], rightFoot:[.22,.08,.04] };
const g=(name:string,w:number,h:number,d:number,anchor:Anchor="torso",p:[number,number,number]=[0,0,0],material="fabric"):ConstructionGroup=>({name,width:w,height:h,depth:d,position:{x:p[0],y:p[1],z:p[2]},material,triangles:12,anchor});

/** The browser-side deterministic compiler used by the active preview (not a metadata adapter). */
export function compileRenderedConstruction(item:{id:string;kind:string;colors:string[];size:string;material?:unknown}):ConstructionItem {
 const big=item.kind==="oversized_hoodie", k=item.kind, groups:ConstructionGroup[]=[];
 if (["hoodie","oversized_hoodie","zip_hoodie"].includes(k)) {
  groups.push(g("body_shell",big?1.18:.96,big?.82:.76,big?.42:.34),g("hood",big?.66:.58,.43,big?.4:.34,"neck",[0,.12,-.08]),g("hood_opening",.38,.3,.05,"neck",[0,.1,.16]),g("hood_fold",.48,.1,.16,"neck",[0,-.08,-.17]),g("shoulders",big?1.42:1.2,.1,.34,"torso",[0,.38,0]),g("sleeves",big?1.62:1.42,.5,big?.34:.27,"torso",[0,.08,0]),g("cuffs",big?1.62:1.42,.09,.3,"torso",[0,-.18,0]),g("waistband",big?1.14:.94,.12,.36,"waist",[0,.1,0]),g("drawstrings",.32,.35,.025,"neck",[0,-.1,.22]));
  if(k==="zip_hoodie") groups.push(g("front_left",.46,.7,.05,"torso",[-.24,0,.2]),g("front_right",.46,.7,.05,"torso",[.24,0,.2]),g("zipper",.035,.68,.03,"torso",[0,0,.24],"metal")); else groups.push(g("kangaroo_pocket",.55,.25,.1,"torso",[0,-.16,.22]));
 }
 if(k==="bomber_jacket") groups.push(g("body_shell",1,.62,.44),g("rib_collar",.52,.1,.32,"neck"),g("rib_cuffs",1.45,.1,.3,"torso",[0,-.12,0]),g("rib_waistband",.92,.1,.36,"waist",[0,.18,0]),g("zipper",.035,.55,.03,"torso",[0,0,.25],"metal"));
 if(k==="blazer") groups.push(g("body_shell",1,.82,.3),g("lapel_left",.25,.48,.06,"torso",[-.17,.1,.2]),g("lapel_right",.25,.48,.06,"torso",[.17,.1,.2]),g("shoulders",1.3,.12,.34,"torso",[0,.38,0]),g("front_opening",.08,.55,.04,"torso",[0,-.05,.2]),g("buttons",.06,.24,.05,"torso",[.1,-.1,.23],"metal"),g("formal_hem",.96,.08,.3,"waist",[0,.1,0]));
 if(k==="puffer_jacket") { groups.push(g("inflated_shell",1.16,.86,.52),g("thick_sleeves",1.58,.58,.38)); for(let i=0;i<6;i++) groups.push(g(`quilt_sections:${i+1}`,1.12,.09,.04,"torso",[0,.34-i*.135,.29])); }
 if(k==="cargo_pants") groups.push(g("leg_left",.38,.88,.34,"leftLeg"),g("leg_right",.38,.88,.34,"rightLeg"),g("waistband",.86,.12,.34,"waist"),g("cargo_pocket_left",.24,.25,.1,"leftLeg",[-.19,.08,.2]),g("cargo_pocket_right",.24,.25,.1,"rightLeg",[.19,.08,.2]),g("seams",.76,.035,.03,"waist",[0,-.16,.2]),g("hems",.82,.08,.34,"waist",[0,-.7,0]));
 if(["shoes","sneakers","boots"].includes(k)) for(const [side,a] of [["left","leftFoot"],["right","rightFoot"]] as const) groups.push(g(`shoe_${side}`,.38,.2,.62,a,[0,0,.12]),g(`sole_${side}`,.4,.07,.66,a,[0,-.1,.12],"rubber"),g(`upper_${side}`,.36,.16,.48,a,[0,.03,.08]),g(`toe_box_${side}`,.36,.14,.24,a,[0,0,.28]),g(`heel_${side}`,.34,.2,.16,a,[0,.04,-.18]),g(`tongue_${side}`,.2,.16,.24,a,[0,.1,.04]),g(`laces_${side}`,.24,.04,.25,a,[0,.13,.1],"laces"));
 if(k.includes("hair")) groups.push(g("hair_front",.5,.38,.18,"head",[0,.08,.2],"hair"),g("hair_side_left",.18,k==="long_hair"?.82:.42,.34,"head",[-.3,-.15,0],"hair"),g("hair_side_right",.18,k==="long_hair"?.82:.42,.34,"head",[.3,-.15,0],"hair"),g("hair_rear",.58,k==="long_hair"?.9:.45,.2,"head",[0,-.2,-.2],"hair"),g("hair_crown",.58,.22,.5,"head",[0,.22,0],"hair"));
 return {itemId:item.id,kind:k,color:item.colors[0]??"#777777",groups};
}

export function materializeConstruction(item:ConstructionItem){ const root=new THREE.Group(); root.name=`construction:${item.itemId}`; for(const spec of item.groups){ const geometry=new THREE.BoxGeometry(spec.width,spec.height,spec.depth); const material=new THREE.MeshStandardMaterial({color:item.color,roughness:spec.material==="metal"?.25:.72}); material.name=spec.material; const mesh=new THREE.Mesh(geometry,material); mesh.name=spec.name; const a=AVATAR_ANCHORS[spec.anchor]; mesh.position.set(a[0]+spec.position.x,a[1]+spec.position.y,a[2]+spec.position.z); mesh.userData={itemId:item.itemId,groupName:spec.name,anchor:spec.anchor,expected:[spec.width,spec.height,spec.depth]}; root.add(mesh); } return root; }
type ConstructionRoot = ReturnType<typeof materializeConstruction>;
export function disposeConstruction(root:ConstructionRoot){root.traverse((o:any)=>{if(o instanceof THREE.Mesh){o.geometry.dispose(); const m=o.material; (Array.isArray(m)?m:[m]).forEach(x=>x.dispose());}})}
export function verifyRenderedConstruction(generationId:string,items:ConstructionItem[],root:ConstructionRoot):RenderedGeometryVerificationReport { root.updateMatrixWorld(true); const measurements:RenderedMeasurement[]=[],missingGroups:string[]=[]; for(const item of items) for(const spec of item.groups){const object=root.getObjectByName(spec.name); if(!object){missingGroups.push(`${item.itemId}:${spec.name}`);continue;} const size=new THREE.Box3().setFromObject(object).getSize(new THREE.Vector3()), p=object.getWorldPosition(new THREE.Vector3()), expected:[number,number,number]=[spec.width,spec.height,spec.depth], rendered:[number,number,number]=[size.x,size.y,size.z]; measurements.push({itemId:item.itemId,groupName:spec.name,expected,rendered,worldPosition:[p.x,p.y,p.z],triangles:object instanceof THREE.Mesh&&object.geometry.index?object.geometry.index.count/3:12,material:object instanceof THREE.Mesh&&!Array.isArray(object.material)?object.material.name:"",passed:rendered.every((v,i)=>Math.abs(v-expected[i])<=.015)}); } return {generationId,measurements,missingGroups,passed:missingGroups.length===0&&measurements.every(x=>x.passed)}; }
