import * as THREE from "three";

export const SHAPE_TYPES = ["box","rounded_box","capsule","cylinder","tapered_cylinder","extruded_profile","curved_panel","lofted_shell","tube","plane","custom_buffer_geometry"] as const;
export type ShapeType = typeof SHAPE_TYPES[number];
export type Anchor = "head"|"face"|"neck"|"torso"|"back"|"waist"|"leftShoulder"|"rightShoulder"|"leftUpperArm"|"rightUpperArm"|"leftWrist"|"rightWrist"|"leftHip"|"rightHip"|"leftLeg"|"rightLeg"|"leftFoot"|"rightFoot";
export type ConstructionGroup = { name:string; shape:ShapeType; width:number; height:number; depth:number; position:{x:number;y:number;z:number}; rotation:{x:number;y:number;z:number}; material:string; triangles:number; anchor:Anchor; parameters:Record<string,number|string|boolean> };
export type ConstructionItem = { itemId:string; kind:string; color:string; groups:ConstructionGroup[] };
export type RenderedMeasurement = { itemId:string;groupName:string;expected:[number,number,number];rendered:[number,number,number];worldPosition:[number,number,number];triangles:number;material:string;passed:boolean };
export type RenderedGeometryVerificationReport = { generationId:string;passed:boolean;measurements:RenderedMeasurement[];missingGroups:string[] };
export type RepairRecord = { attempt:number;itemId:string;groupName:string;reason:string;before?:RenderedMeasurement;after?:RenderedMeasurement;accepted:boolean };

export const AVATAR_ANCHORS:Record<Anchor,[number,number,number]>={head:[0,2.05,0],face:[0,2.05,.24],neck:[0,1.72,0],torso:[0,1.35,0],back:[0,1.4,-.25],waist:[0,.82,0],leftShoulder:[-.52,1.58,0],rightShoulder:[.52,1.58,0],leftUpperArm:[-.68,1.32,0],rightUpperArm:[.68,1.32,0],leftWrist:[-.72,.95,0],rightWrist:[.72,.95,0],leftHip:[-.22,.82,0],rightHip:[.22,.82,0],leftLeg:[-.22,.48,0],rightLeg:[.22,.48,0],leftFoot:[-.22,.08,.04],rightFoot:[.22,.08,.04]};
const g=(name:string,shape:ShapeType,w:number,h:number,d:number,anchor:Anchor="torso",p:[number,number,number]=[0,0,0],material="fabric",parameters:Record<string,number|string|boolean>={}):ConstructionGroup=>({name,shape,width:w,height:h,depth:d,position:{x:p[0],y:p[1],z:p[2]},rotation:{x:0,y:0,z:0},material,triangles:parameters.budget as number||700,anchor,parameters});

/** Canonical deterministic construction compiler. Its output is consumed verbatim by materializeConstruction. */
export function compileRenderedConstruction(item:{id:string;kind:string;colors:string[];size:string;material?:unknown}):ConstructionItem{
 const k=item.kind,big=k==="oversized_hoodie",groups:ConstructionGroup[]=[];
 if(["hoodie","oversized_hoodie","zip_hoodie"].includes(k)){
  groups.push(g("body_shell","lofted_shell",big?1.2:.98,big?.86:.78,big?.48:.38,"torso",[0,0,0],"fabric",{topScale:big?.86:.92,shoulderDrop:big?.12:.06}),g("hood","curved_panel",big?.7:.62,.47,big?.46:.39,"neck",[0,.13,-.08],"fabric",{opening:.58}),g("hood_opening","tube",.4,.32,.07,"neck",[0,.1,.17],"rib",{arc:.72}),g("hood_fold","tube",.53,.12,.2,"neck",[0,-.08,-.16],"fabric",{arc:.58}),g("sleeve_left","tapered_cylinder",big?.38:.3,big?.65:.58,big?.38:.3,"leftUpperArm",[-.03,-.03,0],"fabric",{topRadius:.62}),g("sleeve_right","tapered_cylinder",big?.38:.3,big?.65:.58,big?.38:.3,"rightUpperArm",[.03,-.03,0],"fabric",{topRadius:.62}),g("cuff_left","cylinder",.31,.11,.31,"leftWrist",[0,0,0],"rib"),g("cuff_right","cylinder",.31,.11,.31,"rightWrist",[0,0,0],"rib"),g("waistband","rounded_box",big?1.15:.95,.13,big?.43:.37,"waist",[0,.1,0],"rib"),g("drawstring_left","tube",.035,.38,.035,"neck",[-.1,-.12,.23],"cord"),g("drawstring_right","tube",.035,.38,.035,"neck",[.1,-.12,.23],"cord"));
  if(k==="zip_hoodie")groups.push(g("front_left","curved_panel",.46,.72,.07,"torso",[-.245,0,.21]),g("front_right","curved_panel",.46,.72,.07,"torso",[.245,0,.21]),g("zipper","rounded_box",.035,.7,.035,"torso",[0,0,.25],"metal"));else groups.push(g("kangaroo_pocket","extruded_profile",.58,.26,.11,"torso",[0,-.16,.23],"fabric",{profile:"kangaroo"}));
 }
 if(k==="blazer")groups.push(g("body_shell","lofted_shell",1.02,.88,.34,"torso",[0,-.04,0],"woven",{topScale:1.08}),g("lapel_left","extruded_profile",.3,.53,.075,"torso",[-.18,.1,.2],"woven",{profile:"lapel_left"}),g("lapel_right","extruded_profile",.3,.53,.075,"torso",[.18,.1,.2],"woven",{profile:"lapel_right"}),g("shoulder_left","rounded_box",.34,.14,.39,"leftShoulder"),g("shoulder_right","rounded_box",.34,.14,.39,"rightShoulder"),g("front_opening","plane",.08,.6,.01,"torso",[0,-.05,.23]),g("button_top","cylinder",.07,.035,.07,"torso",[.1,-.04,.25],"metal"),g("button_bottom","cylinder",.07,.035,.07,"torso",[.1,-.2,.25],"metal"),g("formal_hem","rounded_box",1,.1,.34,"waist",[0,.03,0]));
 if(k==="puffer_jacket"){groups.push(g("inflated_shell","lofted_shell",1.2,.9,.58,"torso",[0,0,0],"nylon",{topScale:.92}),g("sleeve_left","capsule",.4,.68,.4,"leftUpperArm",[0,-.02,0],"nylon"),g("sleeve_right","capsule",.4,.68,.4,"rightUpperArm",[0,-.02,0],"nylon"),g("puffer_collar","tube",.62,.2,.42,"neck",[0,0,0],"nylon"));for(let i=0;i<6;i++)groups.push(g(`quilt_sections:${i+1}`,"capsule",1.14,.115,.075,"torso",[0,.35-i*.14,.32],"nylon",{budget:500}));}
 if(k==="cargo_pants")groups.push(g("leg_left","tapered_cylinder",.42,.9,.38,"leftLeg",[0,0,0],"twill",{topRadius:.78}),g("leg_right","tapered_cylinder",.42,.9,.38,"rightLeg",[0,0,0],"twill",{topRadius:.78}),g("waistband","rounded_box",.9,.14,.38,"waist"),g("cargo_pocket_left","extruded_profile",.28,.27,.13,"leftHip",[-.13,-.2,.22],"twill",{profile:"pocket"}),g("cargo_pocket_right","extruded_profile",.28,.27,.13,"rightHip",[.13,-.2,.22],"twill",{profile:"pocket"}),g("pocket_flap_left","curved_panel",.29,.08,.04,"leftHip",[-.13,-.05,.3]),g("pocket_flap_right","curved_panel",.29,.08,.04,"rightHip",[.13,-.05,.3]),g("hems","rounded_box",.84,.08,.36,"waist",[0,-.7,0]));
 if(["shoes","sneakers","boots"].includes(k))for(const [side,a] of [["left","leftFoot"],["right","rightFoot"]] as const)groups.push(g(`sole_${side}`,"rounded_box",.4,.075,.68,a,[0,-.1,.13],"rubber"),g(`upper_${side}`,"lofted_shell",.37,.18,.49,a,[0,.02,.08],"leather",{topScale:.72}),g(`toe_box_${side}`,"capsule",.37,.15,.27,a,[0,0,.29],"leather"),g(`heel_${side}`,"rounded_box",.35,.22,.18,a,[0,.04,-.18],"leather"),g(`tongue_${side}`,"curved_panel",.22,.18,.25,a,[0,.1,.05],"leather"),g(`laces_${side}`,"tube",.25,.045,.27,a,[0,.14,.11],"laces"));
 if(k.includes("hair")){const long=k==="long_hair";groups.push(g("hair_front","curved_panel",.52,.36,.2,"face",[0,.08,-.02],"hair",{curve:.22}),g("hair_side_left","lofted_shell",.2,long?.84:.43,.36,"head",[-.3,-.16,0],"hair",{topScale:.72}),g("hair_side_right","lofted_shell",.2,long?.84:.43,.36,"head",[.3,-.16,0],"hair",{topScale:.72}),g("hair_rear_left","curved_panel",.28,long?.92:.46,.22,"head",[-.15,-.22,-.21],"hair"),g("hair_rear_right","curved_panel",.28,long?.92:.46,.22,"head",[.15,-.22,-.21],"hair"),g("hair_crown","capsule",.6,.25,.52,"head",[0,.22,0],"hair"));}
 if(k==="wings")for(const side of [-1,1] as const)groups.push(g(side<0?"wing_left":"wing_right","custom_buffer_geometry",item.size==="large"?1.35:item.size==="small"?.75:1.05,.9,.12,"back",[side*(item.size==="large"?.72:.55),.05,-.08],"feather",{profile:"wing",mirror:side}));
 if(k==="backpack")groups.push(g("backpack_body","lofted_shell",.72,.78,.36,"back",[0,-.05,-.2],"canvas",{topScale:.82}),g("strap_left","tube",.12,.75,.1,"back",[-.25,0,.18],"canvas"),g("strap_right","tube",.12,.75,.1,"back",[.25,0,.18],"canvas"));
 return {itemId:item.id,kind:k,color:item.colors[0]??"#777777",groups};
}

function normalize(geometry:any,w:number,h:number,d:number){geometry.computeVertexNormals();geometry.computeBoundingBox();const s=geometry.boundingBox.getSize(new THREE.Vector3());geometry.scale(w/(s.x||1),h/(s.y||1),d/(s.z||1));geometry.center();geometry.computeBoundingBox();geometry.computeVertexNormals();return geometry;}
/** Browser-independent reusable shape factory. All output is normalized to the compiler's exact bounds. */
export function buildShapeGeometry(spec:ConstructionGroup){const w=spec.width,h=spec.height,d=spec.depth;let q:any;
 switch(spec.shape){
  case"box":q=new THREE.BoxGeometry(1,1,1);break;case"rounded_box":q=new THREE.CapsuleGeometry(.38,.35,4,10);q.rotateZ(Math.PI/2);break;case"capsule":q=new THREE.CapsuleGeometry(.5,.8,6,12);break;case"cylinder":q=new THREE.CylinderGeometry(.5,.5,1,16);break;case"tapered_cylinder":q=new THREE.CylinderGeometry(.38,.5,1,16);break;
  case"plane":q=new THREE.BoxGeometry(1,1,.01);break;case"tube":{const c=new THREE.CatmullRomCurve3([new THREE.Vector3(0,.5,0),new THREE.Vector3(.08,0,.08),new THREE.Vector3(0,-.5,0)]);q=new THREE.TubeGeometry(c,12,.08,6,false);break;}
  case"extruded_profile":{const s=new THREE.Shape();s.moveTo(-.5,-.5);s.lineTo(.5,-.5);s.lineTo(.42,.35);s.lineTo(0,.5);s.lineTo(-.42,.35);s.closePath();q=new THREE.ExtrudeGeometry(s,{depth:.15,bevelEnabled:true,bevelSize:.04,bevelThickness:.03,bevelSegments:2});break;}
  case"curved_panel":{const s=new THREE.Shape();s.moveTo(-.5,-.45);s.quadraticCurveTo(0,-.58,.5,-.45);s.lineTo(.45,.42);s.quadraticCurveTo(0,.58,-.45,.42);s.closePath();q=new THREE.ExtrudeGeometry(s,{depth:.12,bevelEnabled:true,bevelSize:.025,bevelThickness:.025,bevelSegments:2});break;}
  case"lofted_shell":q=new THREE.CylinderGeometry(.42,.5,1,16,3,false);break;
  case"custom_buffer_geometry":{const s=new THREE.Shape();s.moveTo(0,-.5);s.bezierCurveTo(.45,-.3,.55,.05,.28,.5);s.bezierCurveTo(.05,.32,-.25,.15,-.5,0);s.bezierCurveTo(-.2,-.08,-.08,-.3,0,-.5);q=new THREE.ExtrudeGeometry(s,{depth:.08,bevelEnabled:true,bevelSegments:1});break;}
 }
 return normalize(q,w,h,d);
}
export function materializeConstruction(item:ConstructionItem){const root=new THREE.Group();root.name=`construction:${item.itemId}`;for(const spec of item.groups){const geometry=buildShapeGeometry(spec);const material=new THREE.MeshStandardMaterial({color:item.color,roughness:spec.material==="metal"?.25:.72,side:spec.shape==="plane"?THREE.DoubleSide:THREE.FrontSide});material.name=spec.material;const mesh=new THREE.Mesh(geometry,material);mesh.name=spec.name;const a=AVATAR_ANCHORS[spec.anchor];mesh.position.set(a[0]+spec.position.x,a[1]+spec.position.y,a[2]+spec.position.z);mesh.rotation.set(spec.rotation.x,spec.rotation.y,spec.rotation.z);mesh.userData={itemId:item.itemId,groupName:spec.name,shape:spec.shape,anchor:spec.anchor,expected:[spec.width,spec.height,spec.depth]};root.add(mesh);}return root;}
type ConstructionRoot=ReturnType<typeof materializeConstruction>;
export function disposeConstruction(root:ConstructionRoot){root.traverse((o:any)=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const m=o.material;(Array.isArray(m)?m:[m]).forEach(x=>x.dispose());}});}
export function verifyRenderedConstruction(generationId:string,items:ConstructionItem[],root:ConstructionRoot):RenderedGeometryVerificationReport{root.updateMatrixWorld(true);const measurements:RenderedMeasurement[]=[],missingGroups:string[]=[];for(const item of items)for(const spec of item.groups){const object=root.getObjectByName(spec.name);if(!object){missingGroups.push(`${item.itemId}:${spec.name}`);continue;}const size=new THREE.Box3().setFromObject(object).getSize(new THREE.Vector3()),p=object.getWorldPosition(new THREE.Vector3()),expected:[number,number,number]=[spec.width,spec.height,spec.depth],rendered:[number,number,number]=[size.x,size.y,size.z];measurements.push({itemId:item.itemId,groupName:spec.name,expected,rendered,worldPosition:[p.x,p.y,p.z],triangles:object instanceof THREE.Mesh?(object.geometry.index?.count??object.geometry.attributes.position.count)/3:0,material:object instanceof THREE.Mesh&&!Array.isArray(object.material)?object.material.name:"",passed:rendered.every((v,i)=>Math.abs(v-expected[i])<=.015)});}return{generationId,measurements,missingGroups,passed:missingGroups.length===0&&measurements.every(x=>x.passed)};}
/** Repairs only failed live groups and accepts a patch only when that group passes remeasurement. */
export function repairRenderedConstruction(generationId:string,items:ConstructionItem[],root:ConstructionRoot,maxAttempts=2){const records:RepairRecord[]=[];let report=verifyRenderedConstruction(generationId,items,root);for(let attempt=1;attempt<=maxAttempts&&!report.passed;attempt++){for(const item of items)for(const spec of item.groups){const before=report.measurements.find(m=>m.itemId===item.itemId&&m.groupName===spec.name);if(before?.passed)continue;const old=root.getObjectByName(spec.name),parent=old?.parent??root.getObjectByName(`construction:${item.itemId}`)??root;old?.parent?.remove(old);const replacement=materializeConstruction({...item,groups:[spec]}).children[0];parent.add(replacement);const next=verifyRenderedConstruction(generationId,items,root),after=next.measurements.find(m=>m.itemId===item.itemId&&m.groupName===spec.name);records.push({attempt,itemId:item.itemId,groupName:spec.name,reason:old?"bounds_outside_tolerance":"missing_group",before,after,accepted:Boolean(after?.passed)});report=next;}}return{report,records};}
