kind = "web"
previewPath = "/"
title = "My Skins"
version = "1.0.0"
id = "artifacts/my-skins"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23443

[services.development]
run = "pnpm --filter @workspace/my-skins run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/my-skins", "run", "build" ]
publicDir = "artifacts/my-skins/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23443"
BASE_PATH = "/"
