CREATE TABLE IF NOT EXISTS "artifact_objects" (
  "id" text PRIMARY KEY NOT NULL,
  "generation_id" text NOT NULL,
  "source_spec_id" text,
  "export_job_id" text,
  "project_id" text NOT NULL,
  "user_id" text NOT NULL,
  "parent_consent_state" text NOT NULL DEFAULT 'not_required',
  "item_id" text,
  "artifact_class" text NOT NULL,
  "pipeline_version" text NOT NULL,
  "compiler_version" text NOT NULL,
  "model_version" text,
  "seed" text,
  "sha256" text NOT NULL,
  "mime_type" text NOT NULL,
  "byte_size" integer NOT NULL,
  "width" integer,
  "height" integer,
  "object_path" text NOT NULL,
  "moderation_decision" text NOT NULL DEFAULT 'pending',
  "rights_decision" text NOT NULL DEFAULT 'pending',
  "quarantined" boolean NOT NULL DEFAULT false,
  "quarantine_reason" text,
  "validation_report" text,
  "publication_refs" text[] NOT NULL DEFAULT '{}',
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "retention_deadline" timestamp with time zone,
  "deleted_at" timestamp with time zone
);
