import type { GarmentCategory, GarmentFit, GarmentMaterial } from "./garment-manifest.ts";
export type GarmentSlot = "top" | "bottom" | "onePiece" | "footwear";
export type ShellKey = "hoodie" | "top" | "jersey" | "jacket" | "bottom" | "cargo" | "shorts" | "dress" | "shoe" | "boot";
export type GarmentDefinition = { category: GarmentCategory; slot: GarmentSlot; shell: ShellKey; variants: readonly string[]; requiredModules: readonly string[]; optionalModules: readonly string[]; materials: readonly GarmentMaterial[]; defaultFit: GarmentFit; classicExport: "shirt" | "pants" | null; validation: { requiredEvidence: readonly string[]; forbiddenEvidence?: readonly string[] }; fallback: GarmentCategory };
const d = (definition: GarmentDefinition) => definition;
export const GARMENT_REGISTRY: Record<GarmentCategory, GarmentDefinition> = {
  hoodie:d({category:"hoodie",slot:"top",shell:"hoodie",variants:["pullover"],requiredModules:["hood","hood-opening","kangaroo-pocket","rib-cuffs","rib-hem"],optionalModules:["drawstrings"],materials:["cotton-fleece","knitted"],defaultFit:"relaxed",classicExport:"shirt",validation:{requiredEvidence:["torso-volume","hood-silhouette","lower-hem"]},fallback:"sweatshirt"}),
  "zip-hoodie":d({category:"zip-hoodie",slot:"top",shell:"hoodie",variants:["full-zip"],requiredModules:["hood","hood-opening","zipper","side-pockets","rib-cuffs","rib-hem"],optionalModules:["drawstrings"],materials:["cotton-fleece"],defaultFit:"relaxed",classicExport:"shirt",validation:{requiredEvidence:["hood-silhouette","zipper","lower-hem"]},fallback:"jacket"}),
  tshirt:d({category:"tshirt",slot:"top",shell:"top",variants:["crew-neck"],requiredModules:["collar","short-sleeves","sleeve-hems","lower-hem"],optionalModules:["chest-pocket"],materials:["cotton-jersey","performance-mesh"],defaultFit:"regular",classicExport:"shirt",validation:{requiredEvidence:["collar-opening","connected-sleeves","lower-hem"],forbiddenEvidence:["hood-silhouette","kangaroo-pocket"]},fallback:"sweatshirt"}),
  sweatshirt:d({category:"sweatshirt",slot:"top",shell:"top",variants:["crew-neck"],requiredModules:["collar","long-sleeves","rib-cuffs","rib-hem"],optionalModules:[],materials:["cotton-fleece","knitted"],defaultFit:"relaxed",classicExport:"shirt",validation:{requiredEvidence:["collar-opening","connected-sleeves","lower-hem"],forbiddenEvidence:["hood-silhouette"]},fallback:"tshirt"}),
  "football-jersey":d({category:"football-jersey",slot:"top",shell:"jersey",variants:["numbered"],requiredModules:["collar","short-sleeves","sleeve-hems","lower-hem"],optionalModules:["number-panel"],materials:["performance-mesh"],defaultFit:"athletic",classicExport:"shirt",validation:{requiredEvidence:["jersey-silhouette","number-panel","lower-hem"]},fallback:"tshirt"}),
  jacket:d({category:"jacket",slot:"top",shell:"jacket",variants:["zip","formal","winter","armoured"],requiredModules:["collar","zipper","long-sleeves","simple-cuffs","lower-hem"],optionalModules:["lapels","side-pockets","armour-plates"],materials:["canvas","wool","leather-like","armour"],defaultFit:"structured",classicExport:"shirt",validation:{requiredEvidence:["structured-shoulders","front-opening","lower-hem"]},fallback:"sweatshirt"}),
  jeans:d({category:"jeans",slot:"bottom",shell:"bottom",variants:["straight"],requiredModules:["waistband","fly","front-pockets","side-seams","inseams"],optionalModules:["belt-loops","back-pockets"],materials:["denim"],defaultFit:"regular",classicExport:"pants",validation:{requiredEvidence:["waistband","leg-continuity","ankle-opening"]},fallback:"trousers"}),
  trousers:d({category:"trousers",slot:"bottom",shell:"bottom",variants:["straight","formal","warm","ninja","pyjama","armoured"],requiredModules:["waistband","side-seams","inseams"],optionalModules:["fly","front-pockets","armour-plates"],materials:["wool","cotton-jersey","canvas","armour"],defaultFit:"regular",classicExport:"pants",validation:{requiredEvidence:["waistband","leg-continuity","ankle-opening"]},fallback:"jeans"}),
  joggers:d({category:"joggers",slot:"bottom",shell:"bottom",variants:["cuffed"],requiredModules:["waistband","side-seams","leg-cuffs"],optionalModules:["side-pockets"],materials:["cotton-fleece","knitted"],defaultFit:"relaxed",classicExport:"pants",validation:{requiredEvidence:["waistband","leg-continuity","tapered-cuffs"]},fallback:"trousers"}),
  "cargo-pants":d({category:"cargo-pants",slot:"bottom",shell:"cargo",variants:["relaxed"],requiredModules:["waistband","front-pockets","cargo-pockets","side-seams","inseams"],optionalModules:["leg-cuffs","knee-panels"],materials:["canvas"],defaultFit:"relaxed",classicExport:"pants",validation:{requiredEvidence:["waistband","cargo-pocket-volume","leg-continuity"]},fallback:"trousers"}),
  shorts:d({category:"shorts",slot:"bottom",shell:"shorts",variants:["casual","football"],requiredModules:["waistband","side-seams","shorts-hem"],optionalModules:["number-panel"],materials:["cotton-jersey","performance-mesh","canvas"],defaultFit:"athletic",classicExport:"pants",validation:{requiredEvidence:["waistband","above-knee-hem"],forbiddenEvidence:["ankle-opening"]},fallback:"trousers"}),
  dress:d({category:"dress",slot:"onePiece",shell:"dress",variants:["princess","school","formal"],requiredModules:["collar","waist-seam","skirt-panels","lower-hem"],optionalModules:["short-sleeves","decorative-accents"],materials:["satin-like","cotton-jersey","wool"],defaultFit:"regular",classicExport:"shirt",validation:{requiredEvidence:["continuous-silhouette","skirt-volume","gap-free-waist"],forbiddenEvidence:["separate-leg-shells"]},fallback:"dress"}),
  sneakers:d({category:"sneakers",slot:"footwear",shell:"shoe",variants:["low-top"],requiredModules:["sole","toe-cap"],optionalModules:["laces"],materials:["canvas","leather-like"],defaultFit:"regular",classicExport:null,validation:{requiredEvidence:["foot-coverage"]},fallback:"boots"}),
  boots:d({category:"boots",slot:"footwear",shell:"boot",variants:["ankle","fantasy","formal"],requiredModules:["sole","boot-shaft"],optionalModules:["buckles"],materials:["leather-like","armour"],defaultFit:"regular",classicExport:null,validation:{requiredEvidence:["foot-coverage","ankle-coverage"]},fallback:"sneakers"}),
  "football-boots":d({category:"football-boots",slot:"footwear",shell:"shoe",variants:["studded"],requiredModules:["sole","toe-cap","studs"],optionalModules:["laces"],materials:["leather-like"],defaultFit:"athletic",classicExport:null,validation:{requiredEvidence:["foot-coverage","studs"]},fallback:"sneakers"}),
};
export function getGarment(category: GarmentCategory) { return GARMENT_REGISTRY[category]; }
