import test from "node:test";
import assert from "node:assert/strict";
import { AVATAR_ANCHORS, compileRenderedConstruction, disposeConstruction, materializeConstruction, verifyRenderedConstruction } from "../ai/rendered-construction";

const item=(kind:string)=>({id:`item-${kind}`,kind,colors:["#336699"],size:"medium",material:"cotton"});
test("canonical groups become measured Three meshes",()=>{const construction=compileRenderedConstruction(item("hoodie")); const root=materializeConstruction(construction); const report=verifyRenderedConstruction("generation-1",[construction],root); assert.equal(report.passed,true); assert.ok(root.getObjectByName("hood_fold")); assert.equal(report.measurements.find(x=>x.groupName==="body_shell")?.material,"fabric"); disposeConstruction(root);});
test("families materialize visibly distinct named construction",()=>{assert.notDeepEqual(compileRenderedConstruction(item("hoodie")).groups.map(x=>x.name),compileRenderedConstruction(item("puffer_jacket")).groups.map(x=>x.name)); assert.equal(compileRenderedConstruction(item("puffer_jacket")).groups.filter(x=>x.name.startsWith("quilt_sections:")).length,6); assert.deepEqual(compileRenderedConstruction(item("cargo_pants")).groups.filter(x=>x.name.includes("cargo_pocket")).map(x=>x.name),["cargo_pocket_left","cargo_pocket_right"]);});
test("footwear is symmetric and anchored to feet",()=>{const groups=compileRenderedConstruction(item("sneakers")).groups; const left=groups.find(x=>x.name==="shoe_left")!,right=groups.find(x=>x.name==="shoe_right")!; assert.deepEqual([left.width,left.height,left.depth],[right.width,right.height,right.depth]); assert.equal(left.anchor,"leftFoot"); assert.equal(right.anchor,"rightFoot"); assert.equal(AVATAR_ANCHORS.leftFoot[0],-AVATAR_ANCHORS.rightFoot[0]);});
test("missing live mesh rejects acceptance",()=>{const construction=compileRenderedConstruction(item("long_hair")); const root=materializeConstruction(construction); root.remove(root.getObjectByName("hair_rear")!); const report=verifyRenderedConstruction("generation-2",[construction],root); assert.equal(report.passed,false); assert.deepEqual(report.missingGroups,["item-long_hair:hair_rear"]); disposeConstruction(root);});
