import test from "node:test";
import assert from "node:assert/strict";
import { Vector3 } from "three";
import { AVATAR_ANCHORS, SHAPE_TYPES, buildShapeGeometry, compileRenderedConstruction, disposeConstruction, materializeConstruction, repairRenderedConstruction, verifyRenderedConstruction } from "../ai/rendered-construction";

const item=(kind:string)=>({id:`item-${kind}`,kind,colors:["#336699"],size:"medium",material:"cotton"});
test("canonical groups become measured Three meshes",()=>{const construction=compileRenderedConstruction(item("hoodie")); const root=materializeConstruction(construction); const report=verifyRenderedConstruction("generation-1",[construction],root); assert.equal(report.passed,true); assert.ok(root.getObjectByName("hood_fold")); assert.equal(report.measurements.find(x=>x.groupName==="body_shell")?.material,"fabric"); disposeConstruction(root);});
test("families materialize visibly distinct named construction",()=>{assert.notDeepEqual(compileRenderedConstruction(item("hoodie")).groups.map(x=>x.name),compileRenderedConstruction(item("puffer_jacket")).groups.map(x=>x.name)); assert.equal(compileRenderedConstruction(item("puffer_jacket")).groups.filter(x=>x.name.startsWith("quilt_sections:")).length,6); assert.deepEqual(compileRenderedConstruction(item("cargo_pants")).groups.filter(x=>x.name.includes("cargo_pocket")).map(x=>x.name),["cargo_pocket_left","cargo_pocket_right"]);});
test("footwear is symmetric and anchored to feet",()=>{const groups=compileRenderedConstruction(item("sneakers")).groups; const left=groups.find(x=>x.name==="upper_left")!,right=groups.find(x=>x.name==="upper_right")!; assert.deepEqual([left.width,left.height,left.depth],[right.width,right.height,right.depth]); assert.equal(left.anchor,"leftFoot"); assert.equal(right.anchor,"rightFoot"); assert.equal(AVATAR_ANCHORS.leftFoot[0],-AVATAR_ANCHORS.rightFoot[0]); assert.equal(groups.length,12);});
test("missing live mesh rejects acceptance and local repair restores only it",()=>{const construction=compileRenderedConstruction(item("long_hair")); const root=materializeConstruction(construction); const untouched=root.getObjectByName("hair_crown"); root.remove(root.getObjectByName("hair_rear_left")!); const report=verifyRenderedConstruction("generation-2",[construction],root); assert.equal(report.passed,false); assert.deepEqual(report.missingGroups,["item-long_hair:hair_rear_left"]); const repaired=repairRenderedConstruction("generation-2",[construction],root); assert.equal(repaired.report.passed,true); assert.equal(repaired.records.length,1); assert.equal(root.getObjectByName("hair_crown"),untouched); disposeConstruction(root);});
test("all shape builders produce exact deterministic bounds, normals and stay in budget",()=>{for(const shape of SHAPE_TYPES){const spec={...compileRenderedConstruction(item("hoodie")).groups[0],shape,width:.8,height:.6,depth:.3,triangles:700};const a=buildShapeGeometry(spec),b=buildShapeGeometry(spec);a.computeBoundingBox();b.computeBoundingBox();assert.deepEqual(a.boundingBox,b.boundingBox,shape);const size=a.boundingBox!.getSize(new Vector3());assert.ok(Math.abs(size.x-.8)<1e-6&&Math.abs(size.y-.6)<1e-6&&Math.abs(size.z-.3)<1e-6,shape);assert.ok(a.attributes.normal.count>0,shape);assert.ok((a.index?.count??a.attributes.position.count)/3<=700,shape);a.dispose();b.dispose();}});
test("premium families use recognizable non-box groups",()=>{const hoodie=compileRenderedConstruction(item("hoodie")),zip=compileRenderedConstruction(item("zip_hoodie")),blazer=compileRenderedConstruction(item("blazer")),puffer=compileRenderedConstruction(item("puffer_jacket"));assert.equal(hoodie.groups.find(x=>x.name==="body_shell")?.shape,"lofted_shell");assert.ok(!zip.groups.some(x=>x.name==="kangaroo_pocket"));assert.equal(blazer.groups.filter(x=>x.name.startsWith("lapel_")).length,2);assert.equal(puffer.groups.filter(x=>x.name.startsWith("quilt_sections:")).length,6);});
