import * as THREE from "three";
import type { HoodieGarmentSpec } from "./spec.ts";

export type HoodiePart={name:string;geometry:any;position?:[number,number,number]};
const box=(w:number,h:number,d:number)=>new THREE.BoxGeometry(w,h,d,6,6,4);
export function compileHoodie(spec:HoodieGarmentSpec){
 const c=spec.construction, torsoY=1.5+(1.1-c.torsoLength)/2, sleeveY=1.52-c.shoulderDrop/2;
 const parts:HoodiePart[]=[{name:"torso",geometry:box(c.torsoWidth,c.torsoLength,c.torsoDepth),position:[0,torsoY,0]}];
 for(const side of [-1,1] as const){const x=side*(c.torsoWidth/2+.13);parts.push({name:`${side<0?"left":"right"}-sleeve`,geometry:box(.29*c.sleeveFullness,c.sleeveLength,.48),position:[x,sleeveY,0]},{name:`${side<0?"left":"right"}-cuff`,geometry:box(.27*c.sleeveFullness,c.cuffHeight,.44),position:[x,sleeveY-c.sleeveLength/2-c.cuffHeight/2,0]})}
 parts.push({name:"waistband",geometry:box(c.torsoWidth*.96,c.waistbandHeight,c.torsoDepth*1.01),position:[0,torsoY-c.torsoLength/2-c.waistbandHeight/2,0]});
 const hood=new THREE.SphereGeometry(1,32,20,0,Math.PI*2,0,Math.PI*.72);hood.scale(c.hoodOpeningWidth,c.hoodHeight/2,c.hoodDepth);parts.push({name:"hood",geometry:hood,position:[0,2.15,0]});
 if(c.pocketType==="kangaroo")parts.push({name:"pocket",geometry:box(c.pocketWidth,c.pocketHeight,.06),position:[0,torsoY-.2,c.torsoDepth/2+.035]});
 if(c.pocketType==="two-front")for(const side of [-1,1] as const)parts.push({name:`${side<0?"left":"right"}-pocket`,geometry:box(c.pocketWidth,c.pocketHeight,.06),position:[side*(c.pocketWidth/2+.04),torsoY-.2,c.torsoDepth/2+.035]});
 if(c.drawstringEnabled)for(const side of [-1,1] as const){const curve=new THREE.LineCurve3(new THREE.Vector3(0,0,0),new THREE.Vector3(0,-c.drawstringLength,0));parts.push({name:`${side<0?"left":"right"}-drawstring`,geometry:new THREE.TubeGeometry(curve,8,.012,8),position:[side*c.hoodOpeningWidth*.27,2.11,c.hoodDepth*.72]})}
 return {parts,bounds:Object.fromEntries(parts.map(p=>{p.geometry.computeBoundingBox();const b=p.geometry.boundingBox!.clone();if(p.position)b.translate(new THREE.Vector3(...p.position));return[p.name,b]})),valuesUsed:structuredClone(c)};
}

type Severity="expected-surface-proximity"|"acceptable-overlap"|"severe-clipping";
const avatar={head:new THREE.Box3(new THREE.Vector3(-.3,2.12,-.27),new THREE.Vector3(.3,2.72,.27)),neck:new THREE.Box3(new THREE.Vector3(-.2,1.98,-.2),new THREE.Vector3(.2,2.2,.2)),torso:new THREE.Box3(new THREE.Vector3(-.48,1.02,-.29),new THREE.Vector3(.48,2.02,.29)),leftArm:new THREE.Box3(new THREE.Vector3(-.78,1.0,-.2),new THREE.Vector3(-.5,1.94,.2)),rightArm:new THREE.Box3(new THREE.Vector3(.5,1,-.2),new THREE.Vector3(.78,1.94,.2)),leftWrist:new THREE.Box3(new THREE.Vector3(-.78,.9,-.2),new THREE.Vector3(-.5,1.08,.2)),rightWrist:new THREE.Box3(new THREE.Vector3(.5,.9,-.2),new THREE.Vector3(.78,1.08,.2)),hips:new THREE.Box3(new THREE.Vector3(-.45,.82,-.28),new THREE.Vector3(.45,1.1,.28))};
function measurement(label:string,a:any,b:any){const overlap=new THREE.Vector3(Math.max(0,Math.min(a.max.x,b.max.x)-Math.max(a.min.x,b.min.x)),Math.max(0,Math.min(a.max.y,b.max.y)-Math.max(a.min.y,b.min.y)),Math.max(0,Math.min(a.max.z,b.max.z)-Math.max(a.min.z,b.min.z)));const overlapVolume=overlap.x*overlap.y*overlap.z;const distance=a.distanceToPoint(b.clampPoint(a.getCenter(new THREE.Vector3()),new THREE.Vector3()));const contactExpected=label==="pocket versus torso";const enclosingLayer=/torso versus|sleeves versus/.test(label);const severity:Severity=overlapVolume===0&&!contactExpected&&distance>.08?"severe-clipping":contactExpected||enclosingLayer?"expected-surface-proximity":"acceptable-overlap";return{label,distance:Number(distance.toFixed(4)),overlap:{x:Number(overlap.x.toFixed(4)),y:Number(overlap.y.toFixed(4)),z:Number(overlap.z.toFixed(4)),volume:Number(overlapVolume.toFixed(5))},severity}}
export function analyseHoodieIntersections(spec:HoodieGarmentSpec){const {bounds}=compileHoodie(spec);const union=(names:string[])=>names.reduce((b,n)=>b.union(bounds[n]),new THREE.Box3());return[
 measurement("hood versus head",bounds.hood,avatar.head),measurement("collar versus neck",bounds.torso,avatar.neck),measurement("torso versus avatar torso",bounds.torso,avatar.torso),measurement("sleeves versus arms",union(["left-sleeve","right-sleeve"]),avatar.leftArm.clone().union(avatar.rightArm)),measurement("cuffs versus wrists",union(["left-cuff","right-cuff"]),avatar.leftWrist.clone().union(avatar.rightWrist)),measurement("pocket versus torso",union(Object.keys(bounds).filter(k=>k.includes("pocket"))),bounds.torso),measurement("waistband versus hips",bounds.waistband,avatar.hips),
 ]}
